name: update-image-builder

on:
  push:
    branches: [ master ]

jobs:
  update-image-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Push commit to image-builder repo
        run: |
          git clone "https://${{ secrets.PROW_BOT_TOKEN }}@github.com/open-cluster-management/image-builder.git"
          cd image-builder
          echo "$GITHUB_REPOSITRY@%GITHUB_SHA" > .trigger-openshift-ci"
          git commit -am "update .trigger-openshift-ci" --quiet
          git push --quiet
